/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jumpert.autoethernet;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jpere
 */
public class AutoEthernet extends javax.swing.JFrame {
    private Timer tiempo;
    private int milis=0, seg=0, min=0;
    
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e){
            milis++;
            if (milis == 100) {
                seg++;
                milis= 0;
            }
            if (seg == 60) {
                min++;
                milis=0;
                seg= 0;
            }
            if (min == 10) {
                dispose();
            }
            actualizarTiempo();
        }
    };
    private String etiqueta_tiempo;
    private String timeSec;
    private void actualizarTiempo(){
        String texto = (min<=9?"0":"")+min+":"+(seg<=9?"0":"")+seg+":"+(milis<=9?"0":"")+milis;
        String intStr = (min<=9?"0":"")+min+(seg<=9?"0":"")+seg+(milis<=9?"0":"")+milis;
        etiqueta_tiempo= texto;
        timeSec = intStr;
    }
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form AutoMEthernet
     */
    public AutoEthernet() { 
        initComponents();
        this.setTitle("AUTOMOTIVE ETHERNET");
        SetImageLabel(jLabel2, "src/main/java/images/fondo.jpg");
        tiempo = new Timer(10, acciones);
        tiempo.start();
        setModelo();
        
    }
    
    private void setModelo() {
        String[] header = {"Timestrap", "C", "ID", "Name", "Dir", "D", "Data"};
        model.setColumnIdentifiers(header);
        Tabla.setModel(model);
    }
    
    private void setDato() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        LUCES = new javax.swing.JButton();
        FRENOS = new javax.swing.JButton();
        AIRE = new javax.swing.JButton();
        TREN = new javax.swing.JButton();
        RADARD = new javax.swing.JButton();
        RADART = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        CAMT = new javax.swing.JButton();
        CAMD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(1092, 720));

        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 360));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel1.setText("Automotive Ethernet");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(303, 303, 303))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setLayout(null);

        LUCES.setText("LUCES");
        LUCES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LUCESActionPerformed(evt);
            }
        });
        jPanel4.add(LUCES);
        LUCES.setBounds(35, 10, 90, 22);

        FRENOS.setText("FRENOS");
        FRENOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRENOSActionPerformed(evt);
            }
        });
        jPanel4.add(FRENOS);
        FRENOS.setBounds(35, 40, 90, 22);

        AIRE.setText("P. AIRE");
        AIRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIREActionPerformed(evt);
            }
        });
        jPanel4.add(AIRE);
        AIRE.setBounds(35, 80, 90, 22);

        TREN.setText("TREN");
        TREN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRENActionPerformed(evt);
            }
        });
        jPanel4.add(TREN);
        TREN.setBounds(35, 110, 90, 22);

        RADARD.setText("RADARD");
        RADARD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADARDActionPerformed(evt);
            }
        });
        jPanel4.add(RADARD);
        RADARD.setBounds(35, 150, 90, 22);

        RADART.setText("RADART");
        RADART.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADARTActionPerformed(evt);
            }
        });
        jPanel4.add(RADART);
        RADART.setBounds(35, 180, 90, 22);

        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        jPanel4.add(RESET);
        RESET.setBounds(35, 230, 90, 50);

        CAMT.setText("CAM. T");
        CAMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMTActionPerformed(evt);
            }
        });
        jPanel4.add(CAMT);
        CAMT.setBounds(35, 330, 90, 22);

        CAMD.setText("CAM. D");
        CAMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMDActionPerformed(evt);
            }
        });
        jPanel4.add(CAMD);
        CAMD.setBounds(35, 300, 90, 22);
        jPanel4.add(jLabel2);
        jLabel2.setBounds(30, 0, 1030, 370);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1092, 1092, 1092)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESETActionPerformed

    private void FRENOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRENOSActionPerformed
        // TODO add your handling code here:
        String[] infoFrenos = new String[7];
        infoFrenos[0] = etiqueta_tiempo;
        infoFrenos[1] = "AuE";
        infoFrenos[2] = "Frenos";
        infoFrenos[3] = "Alert";
        infoFrenos[4] = "Tx";
        infoFrenos[5] = "8";
        int num = Integer.parseInt(timeSec);
        infoFrenos[6] = Integer.toHexString(num) + " 00 00 00 00 00 00";
        model.addRow(infoFrenos);
        Tabla.setModel(model);
    }//GEN-LAST:event_FRENOSActionPerformed

    
    private void LUCESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LUCESActionPerformed
        // TODO add your handling code here:
        String[] infoLuces = new String[7];
        infoLuces[0] = etiqueta_tiempo;
        infoLuces[1] = "AuE";
        infoLuces[2] = "Luces";
        infoLuces[3] = "Alert";
        infoLuces[4] = "Tx";
        infoLuces[5] = "8";
        int num = Integer.parseInt(timeSec);
        infoLuces[6] = Integer.toHexString(num) + " 00 00 00 00 00 00";
        model.addRow(infoLuces);
        Tabla.setModel(model);
    }//GEN-LAST:event_LUCESActionPerformed

    private void AIREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIREActionPerformed
        // TODO add your handling code here:
        String[] infoLuces = new String[7];
        infoLuces[0] = etiqueta_tiempo;
        infoLuces[1] = "AuE";
        infoLuces[2] = "Luces";
        infoLuces[3] = "Alert";
        infoLuces[4] = "Tx";
        infoLuces[5] = "8";
        int num = Integer.parseInt(timeSec);
        infoLuces[6] = Integer.toHexString(num) + " 00 00 00 00 00 00";
        model.addRow(infoLuces);
        Tabla.setModel(model);
    }//GEN-LAST:event_AIREActionPerformed

    private void TRENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRENActionPerformed
        // TODO add your handling code here:
        String[] infoLuces = new String[7];
        infoLuces[0] = etiqueta_tiempo;
        infoLuces[1] = "AuE";
        infoLuces[2] = "Luces";
        infoLuces[3] = "Alert";
        infoLuces[4] = "Tx";
        infoLuces[5] = "8";
        int num = Integer.parseInt(timeSec);
        infoLuces[6] = Integer.toHexString(num) + " 00 00 00 00 00 00";
        model.addRow(infoLuces);
        Tabla.setModel(model);
    }//GEN-LAST:event_TRENActionPerformed

    private void RADARDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADARDActionPerformed
        // TODO add your handling code here:
        String[] infoRadarD = new String[7];
        infoRadarD[0] = etiqueta_tiempo;
        infoRadarD[1] = "AuE";
        infoRadarD[2] = "Radar Del.";
        infoRadarD[3] = "Alert";
        infoRadarD[4] = "Tx";
        infoRadarD[5] = "8";
        int num = Integer.parseInt(timeSec);
        infoRadarD[6] = Integer.toHexString(num) + " 00 00 00 00 00 00";
        model.addRow(infoRadarD);
        Tabla.setModel(model);
    }//GEN-LAST:event_RADARDActionPerformed

    private void RADARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADARTActionPerformed
        // TODO add your handling code here:
        String[] infoRadarT = new String[7];
        infoRadarT[0] = etiqueta_tiempo;
        infoRadarT[1] = "AuE";
        infoRadarT[2] = "Radar Tras.";
        infoRadarT[3] = "Alert";
        infoRadarT[4] = "Tx";
        infoRadarT[5] = "8";
        int num = Integer.parseInt(timeSec);
        infoRadarT[6] = Integer.toHexString(num) + " 00 00 00 00 00 00";
        model.addRow(infoRadarT);
        Tabla.setModel(model);
    }//GEN-LAST:event_RADARTActionPerformed

    private void CAMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMDActionPerformed
        // TODO add your handling code here:
        String[] infoCAMD = new String[7];
        infoCAMD[0] = etiqueta_tiempo;
        infoCAMD[1] = "AuE";
        infoCAMD[2] = "Cam. Del.";
        infoCAMD[3] = "Alert";
        infoCAMD[4] = "Tx";
        infoCAMD[5] = "8";
        int num = Integer.parseInt(timeSec);
        infoCAMD[6] = Integer.toHexString(num) + " 00 00 00 00 00 00";
        model.addRow(infoCAMD);
        Tabla.setModel(model);
    }//GEN-LAST:event_CAMDActionPerformed

    private void CAMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMTActionPerformed
        // TODO add your handling code here:
        String[] infoCAMT = new String[7];
        infoCAMT[0] = etiqueta_tiempo;
        infoCAMT[1] = "AuE";
        infoCAMT[2] = "Cam. Tras.";
        infoCAMT[3] = "Alert";
        infoCAMT[4] = "Tx";
        infoCAMT[5] = "8";
        int num = Integer.parseInt(timeSec);
        infoCAMT[6] = Integer.toHexString(num) + " 00 00 00 00 00 00";
        model.addRow(infoCAMT);
        Tabla.setModel(model);
    }//GEN-LAST:event_CAMTActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoEthernet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoEthernet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoEthernet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoEthernet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new AutoEthernet().setVisible(true);
                
            }
        });
    }
    private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AIRE;
    private javax.swing.JButton CAMD;
    private javax.swing.JButton CAMT;
    private javax.swing.JButton FRENOS;
    private javax.swing.JButton LUCES;
    private javax.swing.JButton RADARD;
    private javax.swing.JButton RADART;
    private javax.swing.JButton RESET;
    private javax.swing.JButton TREN;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
